version: '2'
services:
  nginx:
    image: nginx:1-alpine
    volumes:
     - ./src/app/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./src/app/nginx/common:/usr/share/nginx/html/common
    ports:
     - "3000:3000"
    depends_on:
     - team_blue
     - team_green
     - team_red

  team_blue:
    build: ./src/app/team-blue
    ports:
     - "3001:3001"
    volumes:
     - ./src/app/team-blue/src:/code/src

  team_green:
    build: ./src/app/team-green
    ports:
     - "3002:3002"
    volumes:
     - ./src/app/team-green/src:/code/src

  team_red:
    build: ./src/app/team-red
    ports:
     - "3003:3003"
    volumes:
     - ./src/app/team-red/src:/code/src
